#!/bin/sh
# Generate a C file that takes the address of every function declared in
# the given headers (default: all include/ultimate_*_lib.h), so Oscar64
# compiles all of them (it drops functions nothing references). Used by
# `make check`; output on stdout.
#
# The MOD player is checked separately (build/compile_modplay.c): taking
# the address of the audio functions its __interrupt tick calls makes
# Oscar64 reject the tick ("Function too complex for interrupt").
set -e
headers=${*:-include/ultimate_*_lib.h}
fns=$(cat $headers | grep -oE '^[a-z][a-zA-Z_ *]*[ *](uii_[a-z_0-9]+)\(' | grep -oE 'uii_[a-z_0-9]+' | sort -u)
echo '// Generated by tests/gen_compile_all.sh -- do not edit.'
for h in $headers; do echo "#include \"$(basename "$h")\""; done
echo 'void * const uii_all_functions[] = {'
for f in $fns; do echo "	(void *)$f,"; done
echo '};'
echo 'volatile char sink;'
echo 'int main(void)'
echo '{'
echo '	for (char i = 0; i < sizeof(uii_all_functions) / sizeof(void *); i++)'
echo '		sink = (char)(unsigned)uii_all_functions[i];'
echo '	return 0;'
echo '}'
