#!/bin/sh
# Generate a C file that takes the address of every function declared in
# include/ultimate_*_lib.h, so Oscar64 compiles all of them (it drops
# functions nothing references). Used by `make check`; output on stdout.
set -e
fns=$(cat include/ultimate_*_lib.h | grep -oE '^[a-z][a-zA-Z_ *]*[ *](uii_[a-z_0-9]+)\(' | grep -oE 'uii_[a-z_0-9]+' | sort -u)
echo '// Generated by tests/gen_compile_all.sh -- do not edit.'
for h in include/ultimate_*_lib.h; do echo "#include \"$(basename "$h")\""; done
echo 'void * const uii_all_functions[] = {'
for f in $fns; do echo "	(void *)$f,"; done
echo '};'
echo 'volatile char sink;'
echo 'int main(void)'
echo '{'
echo '	for (char i = 0; i < sizeof(uii_all_functions) / sizeof(void *); i++)'
echo '		sink = (char)(unsigned)uii_all_functions[i];'
echo '	return 0;'
echo '}'
